### ISSUE TITLE
`cypherCheck` can only be parsed with `sql` attribute in JSON and YAML

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#388]
Currently, only the following works:

```yaml
      preConditions:
        - onFail: 'CONTINUE'
        - cypherCheck:
            expectedResult: '0'
            sql: MATCH (n:Neo4j) RETURN count(n)
```

But the following should work too:

```yaml
      preConditions:
        - onFail: 'CONTINUE'
        - cypherCheck:
            expectedResult: '0'
            cypher: MATCH (n:Neo4j) RETURN count(n)
```
