### ISSUE TITLE
Fix indentation in changeLog.xml example

### ISSUE THREAD

**Issue by JohnScience** [liquibase/liquibase-neo4j#644]
In <https://neo4j.com/labs/liquibase/docs/quickstart/#__tabbed_1_4>,

```yaml
databaseChangeLog:
- changeSet:
  id: my-movie-init
  author: fbiville
  changes:
  - cypher: 'CREATE (:Movie {title: ''My Life'', genre: ''Comedy''})'
```

the indentation is off, which causes `changeSet:` to be parsed as a `null`.

![Screenshot (7)](https://github.com/user-attachments/assets/e0d98f0e-754a-40ca-baeb-adc0356e34fc)

Other code examples, e.g. <https://neo4j.com/labs/liquibase/docs/reference-features/#__tabbed_1_3>

```
databaseChangeLog:
  - changeSet:
      id: my-movie-init
      author: fbiville
      changes:
        - cypher: 'CREATE (:Movie {title: ''My Life'', genre: ''Comedy''})'
  - changeSet:
      id: translate
      author: fbiville
      changes:
        - cypher: 'MATCH (m:Movie {title: ''My Life''}) SET m.genre = ''Comédie'''
      rollback:
        - cypher: 'MATCH (m:Movie {title: ''My Life''}) SET m.genre = ''Comedy'''
```

demonstrate proper indentation.
